### ISSUE TITLE
Permute for values after scale_dot_product operation

### ISSUE THREAD

**Issue by Tigerrr07** [ajhalthor/Transformer-Neural-Netork#1]
When got new values by scale_dot_product operation, it should permute `values` like before, to exchange max_sequence_length and num_heads dimensions. And then reshape its size. Such that we can make sure for one row of `values`, it comes from many heads.
``` python
values = values.permute(0, 2, 1, 3).reshape(batch_size, max_sequence_length, self.num_heads * self.head_dim)
```

**Comment by ajhalthor** [comment]
You solved my issue. Thanks a ton! I will mention this in my next video with a shoutout. Thanks for being a part of the community :)
